"use client";
import { useState } from "react";
import { CheckCircle2, CreditCard, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
export function PaymentCheckout({ consultationId }: { consultationId: string }) {
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function pay() { setLoading(true); setMessage(""); const response = await fetch("/api/consultations/payment-order", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ consultationId }) }); const result = await response.json() as { error?: string; order?: { id: string }; keyId?: string }; setLoading(false); if (!response.ok) { setMessage(result.error ?? "Payment could not start."); return; } const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.onload = () => { const Razorpay = (window as Window & { Razorpay?: new (options: Record<string, unknown>) => { open: () => void } }).Razorpay; if (!Razorpay || !result.order || !result.keyId) return; new Razorpay({ key: result.keyId, amount: 110000, currency: "INR", name: "Rivanta Realty", description: "One-to-one consultation", order_id: result.order.id, handler: () => setMessage("Payment received. Your executive will confirm the meeting shortly."), theme: { color: "#0F172A" } }).open(); }; document.body.appendChild(script); }
  return <main className="bg-slate-50 py-12"><section className="container-shell mx-auto max-w-xl"><div className="bg-navy p-7 text-white"><p className="text-sm font-bold uppercase tracking-[0.2em] text-brand">One-to-one consultation</p><h1 className="mt-2 text-3xl font-black">Complete your booking</h1></div><div className="bg-white p-7 shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 pb-5"><span className="font-bold text-navy">Refundable consultation token</span><strong className="text-2xl text-navy">Rs. 1,100</strong></div><div className="mt-5 flex gap-3 text-sm leading-6 text-slate-600"><ShieldCheck className="shrink-0 text-green-600" /><p>100% refundable if you are not satisfied with the one-to-one meeting.</p></div>{message && <p className="mt-5 bg-slate-50 p-3 text-sm font-bold text-slate-700">{message}</p>}<Button onClick={pay} disabled={loading} className="mt-6 w-full gap-2"><CreditCard size={18} /> {loading ? "Opening secure checkout..." : "Pay Rs. 1,100 securely"}</Button><p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><CheckCircle2 size={15} className="text-green-600" /> Secure checkout powered by Razorpay.</p></div></section></main>;
}
